version: "3.8"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "10G"
    volumes:
      - ./data:/data
    restart: unless-stopped

